name: Build and Deploy Vite Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version your project requires

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Commit the 'dist' folder to the main branch
      - name: config git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: copy doc folder
        run: |
          cp -r dist/*../doc


      - name: commit doc folder 
        run: |
          git add  ./doc

          git commit -m "Build output committed by GitHub Actions"
          git push origin main
